# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "caldera" do |cfg|
    cfg.vm.box = "madinasoc2030/ubuntu-20.04-desktop-clean-amd64"
    cfg.vm.hostname = "caldera"
    cfg.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    cfg.vm.network :private_network, ip: "192.168.100.100", gateway: "192.168.100.1", dns: "8.8.8.8"
    cfg.vm.network :private_network, ip: "192.168.11.100", gateway: "192.168.11.1", dns: "8.8.8.8"
    cfg.vm.network :private_network, ip: "10.0.10.100", gateway: "10.0.10.1", dns: "8.8.8.8"
    
    cfg.vm.provision "wazuh", type: "shell", path: "scripts_linux/install-wazuh-agent.sh"
    cfg.vm.provision "filebeat_osquery", type: "shell", path: "wazuh_logbeat_osquery/Linux/install.sh"
    cfg.vm.provision "caldera", type: "shell", path: "scripts_linux/install-caldera-docker.sh"
    
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.name = "Caldera_IT_OT_Railway"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      #vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
  
  
  config.vm.define "ubuntu" do |cfg|
    cfg.vm.box = "madinasoc2030/ubuntu-20.04-desktop-clean-amd64"
    cfg.vm.hostname = "ubuntu"
    cfg.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    cfg.vm.network :private_network, ip: "10.0.10.13", gateway: "10.0.10.1", dns: "8.8.8.8"
    cfg.vm.network :private_network, ip: "192.168.100.13", gateway: "192.168.100.1", dns: "8.8.8.8"
    
    
    cfg.vm.provision "wazuh", type: "shell", path: "scripts_linux/install-wazuh-agent.sh"
    cfg.vm.provision "filebeat_osquery", type: "shell", path: "wazuh_logbeat_osquery/Linux/install.sh"    
    cfg.vm.provision :shell, path: "scripts_linux/install-plc-editor.sh"    
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.name = "Ubuntu_IT_OT_Railway"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      #vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
  
  
  config.vm.define "windows" do |cfg|
    cfg.vm.box = "detectionlab/win10"
    cfg.vm.hostname = "windows"
    cfg.vm.boot_timeout = 1200
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 1200
    cfg.winrm.retry_limit = 20
    
    cfg.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    cfg.vm.network :private_network, ip: "192.168.100.100", gateway: "192.168.100.1", dns: "8.8.8.8"
    cfg.vm.network :private_network, ip: "192.168.11.100", gateway: "192.168.11.1", dns: "8.8.8.8"
    cfg.vm.network :private_network, ip: "10.0.10.100", gateway: "10.0.10.1", dns: "8.8.8.8"
    
    
    #cfg.vm.provision "shell", inline: "Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.9-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.9.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.9.msi /q WAZUH_MANAGER='192.168.38.106' WAZUH_REGISTRATION_SERVER='192.168.38.106'", privileged: true
    #cfg.vm.provision "wazuh", type: "shell", path: "scripts/install-wazuh-agent.ps1", privileged: true
    #cfg.vm.provision "reload"
    
    #cfg.vm.provision "calderaAgent", type: "shell", path: "scripts/install-caldera-agent.ps1", privileged: true
    #cfg.vm.provision "file", source: "scripts/caldera_run.bat", destination: "C:/ProgramData/Microsoft/Windows/Start Menu/Programs/StartUp/caldera_run.bat"
    #cfg.vm.provision "file", source: "scripts/install-caldera-agent.ps1", destination: "C:/Users/vagrant/Documents/install-caldera-agent.ps1"
    
    
    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: true, args: "-ip 192.168.40.104 -dns 8.8.8.8 -gateway 192.168.40.1" 
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: false
    # cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-bginfo.ps1", privileged: false
    # cfg.vm.provision "reload"
    # cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    # cfg.vm.provision "shell", path: "scripts/download_palantir_wef.ps1", privileged: false
    cfg.vm.provision "shell", inline: 'wevtutil el | Select-String -notmatch "Microsoft-Windows-LiveId" | Foreach-Object {wevtutil cl "$_"}', privileged: false
    
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: false
    # cfg.vm.provision "shell", path: "scripts/install-redteam.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-choco-extras.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-osquery.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: false
    # cfg.vm.provision "shell", path: "scripts/install-autorunstowineventlog.ps1", privileged: false
    cfg.vm.provision "enable-public-winrm", type: "shell", path: "scripts/enable-winrm.ps1", privileged: false
    cfg.vm.provision "shell", inline: 'cscript c:\windows\system32\slmgr.vbs /dlv', privileged: false
    cfg.vm.provision "shell", inline: 'cscript c:\windows\system32\slmgr.vbs /rearm', privileged: false
    
    #cfg.vm.provision "shell", path: "scripts/install-factoryio.ps1", privileged: true
    
    
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = false
      vb.name = "Windows_IT_OT_Railway"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 8192]
      vb.customize ["modifyvm", :id, "--cpus", 6]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      
    end
  end
end